### ISSUE TITLE
Docker won't build

### ISSUE THREAD

**Issue by Kurt29** [lamtev/build-tools-dockers#11]
There is this issue for your qt Docker
The command '/bin/sh -c apt-get update && apt-get install -y software-properties-common 	&& apt-add-repository -y ppa:beineri/opt-qt57-xenial' returned a non-zero code: 1

Could you fix that and maybe upgrade the Qt version to the LTS one?

https://hub.docker.com/r/lamtev/qt/builds/

**Comment by lamtev** [comment]
@Kurt29 thank you for pointing that out. As I understood, repository maintainer removed Qt 5.7. I've upgraded Qt to 5.9 LTS version. It should work
